from graphics import *
win = GraphWin("Text Entry", 400,400)
P1 = Point(200,50)
text = Text(P1,"Hello, William")
text.draw(win)
win.getMouse()
P2 = Point(200,100)
second = Entry(P2,10)
second.setSize(15)
second.draw(win)
win.getMouse()
u = second.getText()
if u == "YES SIR":
    P3 = Point(200,250)
    newone = Text(P3,u)
    newone.setSize(15)
    newone.draw(win)
    win.getMouse()
    win.close()
else:
    P4 = Point(200,300)
    old = Text(P4,"no!")
    old.draw(win)
    win.getMouse()
    win.close()